'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { studiesService, type Study } from '@/services/studiesService';

interface StudyPageProps {
  params: { id: string };
}

export default function StudyPage({ params }: StudyPageProps) {
  const [study, setStudy] = useState<Study | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchStudy = async () => {
      try {
        setLoading(true);
        const data = await studiesService.getStudyById(params.id);
        setStudy(data);
      } catch (error) {
        setError(error instanceof Error ? error.message : 'Failed to load study');
      } finally {
        setLoading(false);
      }
    };

    fetchStudy();
  }, [params.id]);

  if (loading) {
    return (
      <main className="container">
        <div style={{ textAlign: 'center', padding: '2rem' }}>
          <p>Loading study...</p>
        </div>
      </main>
    );
  }

  if (error || !study) {
    return (
      <main className="container">
        <div style={{ textAlign: 'center', padding: '2rem' }}>
          <h2>Study not found</h2>
          <p>The requested study could not be found.</p>
          <Link href="/studies" className="button button-primary">
            Back to Studies
          </Link>
        </div>
      </main>
    );
  }


  return (
    <main className="container">
      {/* Header */}
      <div style={{ marginBottom: '2rem' }}>
        <Link
          href="/studies"
          style={{
            color: 'var(--text-secondary)',
            fontSize: '0.875rem',
            textDecoration: 'none',
            marginBottom: '1.5rem',
            display: 'inline-flex',
            alignItems: 'center',
            gap: '0.5rem'
          }}
        >
          ← Back to Studies
        </Link>

        <h1 style={{ marginBottom: '1rem', fontSize: '2rem' }}>{study.title}</h1>

        <div style={{
          display: 'flex',
          gap: '1rem',
          fontSize: '0.875rem',
          color: 'var(--text-secondary)',
          marginBottom: '1.5rem',
          flexWrap: 'wrap'
        }}>
          <span><strong>Theme:</strong> {study.theme}</span>
          <span>•</span>
          <span><strong>Duration:</strong> {study.duration_days} days</span>
          <span>•</span>
          <span><strong>Difficulty:</strong> {study.difficulty}</span>
          <span>•</span>
          <span><strong>Audience:</strong> {study.audience}</span>
          <span>•</span>
          <span><strong>Time per session:</strong> {study.estimated_time_per_session}</span>
        </div>

        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1.5rem' }}>
          {study.tags.map(tag => (
            <span
              key={tag}
              style={{
                fontSize: '0.75rem',
                padding: '0.25rem 0.5rem',
                backgroundColor: 'var(--deep-cream)',
                color: 'var(--deep-coffee)',
                borderRadius: '4px'
              }}
            >
              {tag}
            </span>
          ))}
        </div>
      </div>

      {/* Study Description */}
      <div className="card" style={{ marginBottom: '2rem' }}>
        <h2 style={{ marginBottom: '1rem' }}>About This Study</h2>
        <p style={{ lineHeight: '1.6', marginBottom: '1rem' }}>
          {study.description}
        </p>

        <div style={{
          padding: '1rem',
          backgroundColor: 'var(--champagne)',
          borderRadius: '6px',
          borderLeft: '4px solid var(--ultra-fine-gold)'
        }}>
          <h4 style={{ margin: '0 0 0.75rem 0' }}>Pastor's Message</h4>
          <p style={{ margin: 0, fontStyle: 'italic' }}>
            {study.pastor_message}
          </p>
        </div>
      </div>

      {/* Study Metadata */}
      <div className="card" style={{ marginBottom: '2rem' }}>
        <h3 style={{ marginBottom: '1rem' }}>Study Details</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '1rem' }}>
          <div>
            <strong>Study Style:</strong> {study.study_style}
          </div>
          <div>
            <strong>Structure:</strong> {study.study_structure}
          </div>
          <div>
            <strong>Generated by:</strong> {study.generated_by}
          </div>
          <div>
            <strong>Status:</strong> {study.status}
          </div>
          <div>
            <strong>Popularity:</strong> {study.popularity}/10
          </div>
          <div>
            <strong>Created:</strong> {new Date(study.created_at).toLocaleDateString()}
          </div>
        </div>
      </div>

      {/* Coming Soon Section */}
      <div className="card" style={{ textAlign: 'center', padding: '2rem' }}>
        <h3 style={{ marginBottom: '1rem' }}>Detailed Study Content Coming Soon</h3>
        <p style={{ color: 'var(--text-secondary)', marginBottom: '1.5rem' }}>
          Daily study content, scripture passages, discussion questions, and progress tracking will be available soon.
        </p>
        <div style={{ display: 'flex', gap: '1rem', justifyContent: 'center', flexWrap: 'wrap' }}>
          <Link href="/studies" className="button button-secondary">
            Browse Other Studies
          </Link>
          <button className="button button-primary" disabled style={{ opacity: 0.5 }}>
            Start Study (Coming Soon)
          </button>
        </div>
      </div>

    </main>
  );
}